# Generated by Django 5.2.5 on 2025-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldetail',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='professional_details', to='core.event'),
        ),
    ]
