# Generated by Django 5.2.5 on 2025-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_professionaldetail_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
