# Generated by Django 5.2.5 on 2025-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_professionaldetail_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldetail',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='professional_details', to='core.event'),
        ),
    ]
