# Generated by Django 5.2.5 on 2025-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_degree_end_date_alter_degree_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Contact_details',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='academic_details',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.academicdetail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_details',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.professionaldetail'),
        ),
    ]
