# Generated by Django 5.2.5 on 2025-09-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_contact_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Contact_details',
            new_name='contact_details',
        ),
    ]
